from ansi_colors import *


print("\nText colors:")
print("-" * 20 + "\n")
print(text_color.black + "Black" + default)
print(text_color.white + "White" + default)
print(text_color.blue + "Blue" + default)
print(text_color.brown + "Brown" + default)
print(text_color.red + "Red" + default)
print(text_color.green + "Green" + default)
print(text_color.yellow + "Yellow" + default)
print(text_color.magenta + "Magenta" + default)
print(text_color.cyan + "Cyan" + default)

print("\nText colors (light & dark):")
print("-" * 20 + "\n")
print(text_color.light_white + "Light White" + default)
print(text_color.light_grey + "Light Grey" + default)
print(text_color.dark_grey + "Dark Grey" + default)
print(text_color.light_cyan + "Light Cyan" + default)
print(text_color.dark_cyan + "Dark Cyan" + default)
print(text_color.light_magenta + "Light Magenta" + default)
print(text_color.dark_magenta + "Dark Magenta" + default)
print(text_color.light_blue + "Light Blue" + default)
print(text_color.light_red + "Light Red" + default)
print(text_color.light_green + "Light Green" + default)
print(text_color.light_yellow + "Light Yellow" + default)

print("\nHighlight colors:")
print("-" * 20 + "\n")
print(highlight_color.black + "Black" + default)
print(highlight_color.white + text_color.black + "White" + default)
print(highlight_color.blue + "Blue" + default)
print(highlight_color.red + "Red" + default)
print(highlight_color.green + "Green" + default)
print(highlight_color.yellow + "Yellow" + default)
print(highlight_color.magenta + "Magenta" + default)
print(highlight_color.cyan + "Cyan" + default + "\n")

print("\nExtras:")
print("-" * 20 + "\n")
print(extras.blink + text_color.blue + "Blink" + default)
# print(extras.fast_blink + text_color.red + "Fast blink" + default)
print(extras.bold + text_color.yellow + "Bold" + default)
print(extras.underline + text_color.magenta + "Underline" + default)
print(extras.italic + text_color.light_grey + "Italic" + default)
# print(extras.crossed + text_color.brown + "Crossed" + default)
print(extras.faint + text_color.cyan + "Faint" + default)
print(extras.reverse + text_color.red + "Reverse" + default)
